url: "https://mcdowlinguist.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "michael dow" # the name of your site, e.g. ACME Corp.
description: "personal website"
remote_theme: LeNPaul/academic

# Conversion
markdown:    kramdown
highlighter: rouge

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

defaults:
  - scope:
      path: ""
    values:
      lang: en
  - scope:
      path: "fr"
    values:
      lang: fr
