- activity: |
    Grant reviews:
    <ul>
      <li>Insight Development grants, SSHRC (2023, 2024)</li>
      <li>SSHRC doctoral grants, Université de Montréal (2023, 2024)</li>
    </ul>

- activity: |
    Journal reviews:
    <ul>
      <li><i>Journal of Phonetics</i> (2 articles)</li>
      <li><i>Language</i> (1 article)</li>
      <li><i>Journal of French Language Studies</i> (2 articles)</li>
      <li><i>Journal of the Acoustical Society of America</i> (2 articles)</li>
      <li><i>Second Language Research</i> (1 article)</li>
      <li><i>The Mental Lexicon</i> (1 article)</li>
      <li><i>Speech Communication</i> (1 article)</li>
      <li><i>Communication, lettres et sciences du langage</i> (1 article)</li>
      <li><i>Glossa</i> (2 articles)</li>
      <li><i>Lingua</i> (2 articles)</li>
      <li><i>Indiana University Linguistics Club Working Papers Online</i> (2 articles)</li>
      <li><i>Workshop on Immigrant Languages in the Americas Proceedings</i> (1 article)</li>
      <li><i>Actes des français d’ici 2018</i> (1 article)</li>
    </ul>

- activity: |
    Abstract reviews:
    <ul>
      <li>Annual meeting of the Linguistic Society of America</li>
      <li>International Congress of the Phonetic Sciences</li>
      <li>Linguistic Symposium on Romance Languages</li>
      <li>Annual Congress of the Canadian Linguistic Association</li>
      <li>Change and Variation in Canada</li>
    </ul>

- activity: |
    Canadian Linguistic Association committees:
    <ul>
      <li>Program committee</li>
      <li>Student paper committee</li>
      <li><i>ad hoc</i> committee for relations with the Linguistic Society of America</li>
      <li><i>ad hoc</i> committee for the Canadian Linguistics Olympiad</li>
    </ul>