name: Build and Deploy

on:
  push:
    branches:
      - source
  pull_request:
    branches:
      - source

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby and Bundler
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.3
        bundler-cache: true # This caches the Bundler dependencies

    - name: Install Bundler
      run: gem install bundler -v 2.4.22

    - name: Install dependencies
      run: bundle install

    - name: Before script
      run: chmod +x ./script/cibuild

    - name: Build script
      run: "./script/cibuild"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
  
    - name: Deploy to GitHub Pages
      uses: actions/upload-artifact@v3
      with:
        name: _site
        path: _site
  
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: _site
        path: _site
